### ISSUE TITLE
Calculating correlators gives runtime error

### ISSUE THREAD

**Issue by titaschanda** [ITensor/ITensor#113]
Hi,

I was going through the tutorial on calculating local correlators mentioned at the following link:
http://itensor.org/docs.cgi?page=formulas/measure_mps

Everything works fine, but except for <Sx.Sx> or <Sy.Sy> correlators. My codes are given below.

        psi.position(N/2);
        ITensor oc11 = 4.0 * sites.op("Sx", N/2) * sites.op("Sx", N/2 +1);
        ITensor bondket = psi.A(N/2) * psi.A(N/2 + 1);
        ITensor bondbra = dag(prime(bondket,Site));
        auto c11 = (bondbra*oc11*bondket).real();
   
This gives me `ITError` stating `doTask not defined for task Contract and storage types QMixed<Real> QMixed<Real>`.

Can you help me to solve the problem??

**Comment by titaschanda** [comment]
I believe the problem is in the `ITensor oc11 = 4.0 * sites.op("Sx", N/2) * sites.op("Sx", N/2 +1);` line, but failing to solve this.

**Comment by emstoudenmire** [comment]
Hi, thanks for the report. This isn't a bug per se but is an unfortunate design issue with ITensor which we plan to improve in a future version. The issue is that sites.op always returns an IQTensor, which forces us to use some workarounds to deal with operators like "Sx" which are not well-formed IQTensors (so they use a special kind of non-QN-conserving storage etc. etc.).

A solution you can use is to first turn the operators into ITensors, like this:
    ITensor Sx1 = sites.op("Sx",N/2);
    ITensor Sx2 = sites.op("Sx",N/2+1);
then use Sx1 and Sx2 in your code as before.

If that still doesn't work please do let me know.

**Comment by titaschanda** [comment]
Thank you... It works now..
