### ISSUE TITLE
Wrong PBC condition for superconduncting term.

### ISSUE THREAD

**Issue by xichuang** [ITensor/ITensor#118]
Hi Miles.
When using the following code

`    

    int Nx = 4;
    int Ny = 3;
    int N = Nx * Ny;
    auto yperiodic = true;
    auto lattice = squareLattice(Nx, Ny, {"YPeriodic=", yperiodic});
    auto sites = Spinless(N,{"ConserveNf",false});
    Real dD = 0.2;
    auto ampo = AutoMPO(sites);
    for (auto bnd : lattice) {
            ampo += -dD, "Cdag", bnd.s1, "Cdag", bnd.s2;
            ampo += -dD, "C", bnd.s2, "C", bnd.s1;
        }

`

, the pairing between two edges in the y-direction gives, i.e.,
$$dD c_1 c_3$$
But the correct form should be
$$dD c_3 c_1 = -dD c_1 c_3$$.
Change line 38 in ``itensor/mps/lattice/square.h'' to 
`
    if(yperiodic && y == 1) latt.emplace_back(n+Ny-1,n,x,y+Ny,x,y);
`
can fix this issue. This does not modify the hopping terms.
Similar changes should be applied to other lattice files.
Am I right?

**Comment by emstoudenmire** [comment]
Hi, I thought about this issue quite a bit and while I see that this is a simple change and why it fixes the bug you get, the only concern I have is that people might rely on this behavior too much. So then if someone makes a new function that does a different lattice it "breaks" people's code because they didn't know about this subtle issue ahead of time.

So what do you think about the following: in your driver code that makes the AutoMPO, what if you just put a line that checks whether bnd.s1 < bnd.s2 and determines which sign to put in front of the Hamiltonian term that way? Would that also fix your issue?

Thanks for discussing!

**Comment by xichuang** [comment]
Thank you. It works.
