### ISSUE TITLE
MPS bug in overlap

### ISSUE THREAD

**Issue by martenrichter** [ITensor/ITensor#122]
Hi,
I have just started playing around with itensor and I found a bug for overlap, if an MPS has length 1. (I do this to test some algorithm and to increase it later).
Just try:
`auto tmpmps=MPS(1);
  tmpmps.setA(1, ITensor(2.));
  Print(tmpmps);
  Print(tmpmps.norm());
  Print(overlap(tmpmps,tmpmps));`
and you see the problem.
The bug is caused by overlap assuming, that the mps is at least two itensors long.
It handles applies start and end without checking, in case of a MPS of length 1, the itensor is applied twice.
I known it is a very synthetic example, but it can occur, if you want to start simple, when implementing a new algorithm.

Marten

**Comment by emstoudenmire** [comment]
Hi Marten,
Thanks for pointing this out! I will definitely work to fix this case and I'll link to this bug report to close it when it is fixed. For now please see if you can work with cases where the MPS is 2 sites long or more but let me know if this bug is getting in the way of something you were hoping to accomplish.

Best regards,
Miles

**Comment by martenrichter** [comment]
Hi Miles,
the bug will not prevent me from proceeding with my development, now my test case is with two sites. 
I just needed some time to find out, why the calculation was wrong.

Marten

**Comment by emstoudenmire** [comment]
Hi Marten,
I just pushed a fixed for this. Thanks for pointing it out. I added your name to the Contributors list:
http://itensor.org/about.html
