### ISSUE TITLE
IQTensor += method is broken

### ISSUE THREAD

**Issue by mingruyang** [ITensor/ITensor#138]
When I tried to make an hopping IQMPO by hand (instead of using autompo) for the Hubbard sites, I got some inf numbers which appeared randomly in the matrices every time when the program ran.

My code is as follows:
```cpp
#include `"itensor/all.h"

using namespace itensor;
using std::vector;
using std::string;
using std::min;
using std::max;

IQMPO makeHubbardhop(Hubbard const& sites){
    Real t0 = 1.0;
    Real t1 = 2.0;
    Real t2 = 4.0;
        
    auto N = sites.N();
        
    auto hop = IQMPO(sites);
        
    auto links = std::vector<IQIndex>(N+1);
    for(auto n : range(N+1)){
        links.at(n) = IQIndex(nameint("L",n),
                                  Index("Emp",2),  QN("Sz=", 0,"Nf=", 0),
                                  Index("Up +",2), QN("Sz=",+1,"Nf=",+1),
                                  Index("Dn +",2), QN("Sz=",-1,"Nf=",+1),
                                  Index("Up -",2), QN("Sz=",-1,"Nf=",-1),
                                  Index("Dn -",2), QN("Sz=",+1,"Nf=",-1));
    }
    for(auto n : range1(N)){
        auto row = dag(links.at(n-1));//row: link the site before
        auto col = links.at(n);//colum: link the site after
        auto& W = hop.Aref(n);
        W = IQTensor(row,col,dag(sites(n)),prime(sites(n)));
            
        if(n%2 == 0){
            W += sites.op("Id",n) * setElt(row(1),col(1));
            W += sites.op("Id",n) * setElt(row(2),col(2));
            W += sites.op("F",n) * setElt(row(4),col(3));
            W += sites.op("F",n) * setElt(row(6),col(5));
            W += sites.op("F",n) * setElt(row(8),col(7));
            W += sites.op("F",n) * setElt(row(10),col(9));
                
            W += t0 * sites.op("Ntot",n) * setElt(row(1),col(2));
            //W += sites.op("FAdagup",n) * setElt(row(1),col(4));//
            W += sites.op("Adagdn",n) * setElt(row(1),col(6));
            //W += sites.op("FAup",n) * setElt(row(1),col(8));//
            W += sites.op("Adn",n) * setElt(row(1),col(10));
                
            W += t2 * sites.op("Aup",n) * setElt(row(3),col(2));
            W += t1 * sites.op("Aup",n) * setElt(row(4),col(2));
            //W += t2 * sites.op("AdnF",n) * setElt(row(5),col(2));//
            //W += t1 * sites.op("AdnF",n) * setElt(row(6),col(2));//
            W += t2 * sites.op("Adagup",n) * setElt(row(7),col(2));
            W += t1 * sites.op("Adagup",n) * setElt(row(8),col(2));
            //W += t2 * sites.op("AdagdnF",n) * setElt(row(9),col(2));//
            //W += t1 * sites.op("AdagdnF",n) * setElt(row(10),col(2));//
            
            //PrintData(W);
        }
        else{
            W += sites.op("Id",n) * setElt(row(1),col(1));
            W += sites.op("Id",n) * setElt(row(2),col(2));
            W += sites.op("Id",n) * setElt(row(3),col(3));
            W += sites.op("Id",n) * setElt(row(4),col(4));
            W += sites.op("Id",n) * setElt(row(5),col(5));
            W += sites.op("Id",n) * setElt(row(6),col(6));
            W += sites.op("Id",n) * setElt(row(7),col(7));
            W += sites.op("Id",n) * setElt(row(8),col(8));
            W += sites.op("Id",n) * setElt(row(9),col(9));
            W += sites.op("Id",n) * setElt(row(10),col(10));
        }
        //if(flux(W) != QN({  0,1},{0,1},{ 0,-1}))
        //    {
        //    Print(n);
        //    Print(flux(W));
        //    EXIT
        //    }
            
        W.scaleTo(1.);
    }
        
    hop.Aref(1) *= setElt(links.at(0)(1));
    hop.Aref(N) *= setElt(dag(links.at(N))(2));
        
    return hop;
}

int main(){
	int N = 8;
	auto sites = Hubbard(N);
	auto H2e = makeHubbardhop(sites);
	PrintData(H2e);

	return 0;
}
```

**Comment by emstoudenmire** [comment]
Hi Mingru,
Thanks for the report and definitely thanks for providing a complete sample code. I just ran it and I do see nans / uninitialized memory like you report. However, it appears not to be a bug in ITensor but actually an error in the code above.

Running the code above in debug mode, which turns on much more error checking, gives the following error message:
"div(T1)=(Sz=0,Nf=0) must equal div(T2)=(Sz=-2,Nf=2) when adding T1+T2"
So somewhere in the code there is an addition of two IQTensors of different quantum number "flux", which is not allowed.

Running the code in the debugger I see that the error message is thrown from line 43 of your test code. (The line with Adagdn * setElt(row(1),col(6));). 

Here's likely what's causing the error: the convention we use for Hamiltonian MPOs is that each tensor should have zero QN flux. So the flux of the tensor setElt(row(n),col(m)) needs to cancel out the flux of the site operator you multiply it by. If this is not the case, then most likely the pattern of QN sectors defining the link indices is not the correct one to reflect the structure of your IQMPO. Usually what I do is to organize the IQMPO so that all or most operators of the same flux are in the same block of the MPO matrices. Then I can use a simple pattern of QN sectors for the link IQIndices.

Hope that helps. If it does turn out to be a real bug or something is unclear please let me know.

Miles

**Comment by mingruyang** [comment]
Thanks for telling me about this convention!
It's solved by reverse the flux for the link indices.

**Comment by emstoudenmire** [comment]
Yes, good point - I had not noticed that. Yes, the IQIndex going into the constructor to make the IQTensor W should be dag(row) not row I think. Glad you found it, and it sounds like you are quickly becoming an expert on the IQIndex / IQTensor system.

Miles
