### ISSUE TITLE
.generator throws seg fault

### ISSUE THREAD

**Issue by titaschanda** [ITensor/ITensor#162]
Hi,

I am trying to initialize ITensor using `.generator()` member function. But every time it throws segmentation fault saying `doTask called on unallocated store pointer`. I have tried with lambdas as well as with raw functions.

With warm regards,
Titas

**Comment by emstoudenmire** [comment]
Hi Titas,
Thanks for pointing this out. I had left this behavior undefined in the past because it can't work for IQTensors (since an IQTensor also needs information about its "QN flux" to be well-defined). However it should work for plain ITensors so I just added a fix that makes it work as expected. Please try it out and let me know if you still run into any issues. Thanks!

**Comment by titaschanda** [comment]
Hi Miles,

I have just updated ITensor, but now it is failing to compile, on my MacOs with clang++ compiler.

Titas

![image](https://user-images.githubusercontent.com/5068393/45899456-2ae6f000-bddd-11e8-8a5c-d9f91312a3d5.png)

**Comment by emstoudenmire** [comment]
Thanks! Whoops - I mistakenly didn't rebuild the library when I made the most recent change. But it should now be fixed in the latest version - please "git pull", try again, and let me know!

**Comment by titaschanda** [comment]
Thank you!! It works perfectly!! :)
