### ISSUE TITLE
Integer overflow

### ISSUE THREAD

**Issue by mingruyang** [ITensor/ITensor#182]
When the bond dimension of MPS is very large, e.g., 6000, the value of the size of LocalOp will overflow the maximum of the long integer type and thus give a undefined behavior (for my case,it gives negative value.) This will make line 107 area(phi.front().inds()) != size_t(maxsize) in iterativesolvers.h becomes true and throws an error.

**Comment by mingruyang** [comment]
size_t() won't help it.

**Comment by mtfishman** [comment]
Hi Mingru,

Thanks for pointing this out. What is the local site dimension of your MPO? 

Also, do both sides of the check on line 107 overflow (i.e. does either size_t(maxsize) or area(phi.front().inds()) give you the correct result for the size M^2*d^2 of your effective Hamiltonian, where M=6000 is the MPS bond dimension and d is the local site dimension of your MPO)? 

You may need to send me the code you are running to help track down where the overflow is happening.

Right now, the size_ field of LocalOp is type long, we may need to change that if the size you are seeing is larger than that. However, we may be able to avoid calculating that size in davidson anyway. 

Cheers,
Matt

**Comment by emstoudenmire** [comment]
Also, just wanted to mention that as a temporary workaround you should be able to comment out this line of iterativesolvers.h and then everything else should work just fine. It's not an essential line of code, but rather just a check that the input is valid (which it will be inside of our DMRG code). 

But thanks a lot for pointing this out and we'll fix it!

**Comment by mtfishman** [comment]
Yes, I meant to add that as well. Although depending on what is overflowing, maxsize is used elsewhere in davidson so if that is overflowing it could possible cause other problems (though I think the other usage can just be replaced by maxiter_/actual_maxiter).

**Comment by mingruyang** [comment]
Thanks Miles and Matt!

The local site dimension d=4 (just like the Hubbard model). I use a three-site DMRG algorithm but a two-site DMRG with noise can also give such errors in my case, given a larger bond dimension. 

I tried for three times. area(phi.front().inds()) gives me the correct result while size_t(maxsize) is negative, and their absolute values always add up to 2^32= 4,294,967,296. The error messages of the three tries are as follows:
1. bond dimension of MPS = 5984
area(phi.front().inds()) = 2174486784
A.size() = -2120480512
From line 99, file /home/mingruy/itensor/itensor/iterativesolvers.h
davidson: size of initial vector should match linear matrix size
davidson: size of initial vector should match linear matrix size
Aborted (core dumped)
2. bond dimension of MPS = 5590
area(phi.front().inds()) = 2189950080
A.size() = -2105017216
From line 111, file /home/mingruy/itensor/itensor/iterativesolvers.h
davidson: size of initial vector should match linear matrix size
davidson: size of initial vector should match linear matrix size
Aborted (core dumped)
3. bond dimension > 4096 (core dumped before printing out the bond dimension)
area(phi.front().inds()) = 2171705856
A.size() = -2123261440
From line 111, file /home/mingruy/itensor/itensor/iterativesolvers.h
davidson: size of initial vector should match linear matrix size
davidson: size of initial vector should match linear matrix size
Aborted (core dumped)
area(phi.front().inds()) is larger than the maximum of long int, i.e. 2,147,483,647. Since the initial value of size_ is -1, I guess there should be lots of changes if one want to switch to unsigned long or unsigned long long.

**Comment by mtfishman** [comment]
Hi Mingru,

I created what I think should be a fix for the overflow problem in branch "overflow". Could you check to see if it fixes the problem you were seeing?

It is a good point you made that it might be a problem using -1 as the default value for size_ if we switch to an unsigned int. However, I think we can keep that as is, since using size_ with type size_t, assigning it the value -1 converts it to 2^64-1, which I think is still a good default value.

However, I could not seem to recreate the same overflow on my own machine, since on my computer (CentOS 7 desktop, 64-bit) "long int" seems to be 64-bit. Out of curiosity, what machine are you using?

Cheers,
Matt

**Comment by mtfishman** [comment]
On a more fundamental point about how A.size() is being used here in Davidson: The only way for the eigenvalue problem to reach these sort of scales where the "size" becomes 2^32 is using IQTensors, in which case the real size of the sparse matrix problem is presumably much smaller. Right now, we are just naively multiplying the total IQIndex sizes together. It seems like, for IQTensors, there should be a special function that gives the size of the non-zero data, since that is what is relevant for sparse eigensolvers/linear solvers.

**Comment by mtfishman** [comment]
Although now that I think about it, I don't know if there is a way to get the size of the data of a LocalOp without multiplying the tensors together. But maybe we can get maxsize from the data of the input vectors phi, and instead of comparing the sizes of the LocalOp and the vectors in line 107, we can do a check for whether or not the indices are consistent (so that we never have to calculate A.size() in the first place).

**Comment by mingruyang** [comment]
I'm using archlinux 64bit. I'm not sure if it is because I allowed 32-bit
multilib in my system. The weird thing is when I tried a simple short code
that just multiplies the long ints, which should give a result larger than
the maximum of long, I actually didn't get the overflow.

I'm now checking if your solution works. I'll let you know if I get any
conclusion.

Thanks a lot!

**Comment by mingruyang** [comment]
Hi Matt and Miles,
I sent a push request #184 which fix the problem in my system. Actually size_t and long are both 64 bit in my system (LP64). The problem is due to that the return value of size() function in localmpo_mps.h and localmposet.h is int type but not long type. 
Nevertheless, as a more general setting for all platforms, using long might still be a dangerous choice, since long is the same as int, which is 32 bit, in systems such as windows (LLP64. Refer to #100 by Kyungmin.). So a better solution might be change all the related size() function to return size_t type instead of long. A good reference about the integer types in different systems is here: [https://en.cppreference.com/w/cpp/language/types](https://en.cppreference.com/w/cpp/language/types)

**Comment by mtfishman** [comment]
Good catch, I didn't think to look at LocalMPO, LocalMPO_MPS, etc to make sure their size() methods were outputting the correctly sized integers. I added some more changes along those lines in a new push to pull request #183 (as you suggest, I change all of the size() methods to output size_t, which then requires some changes in davidson() to get rid of warnings about comparing signed and unsigned integers). Could you let me know if that pull request/branch "overflow" also correctly fixes your problem?

**Comment by mingruyang** [comment]
Yes, it works.
