### ISSUE TITLE
Order versus rank (for number of indices)

### ISSUE THREAD

**Issue by emstoudenmire** [ITensor/ITensor#205]
Calling the number of indices the "rank" can be confusing when compared to matrix rank (or tensor train rank [= bond dimension] in the math literature). Because rank already has that accepted meaning, calling the number of indices the "order" of the tensor could be a good alternative. But there could be other alternatives (ninds?). Also we don't have to follow the mathematics convention.

Also there's the question of what we should replace `T.r()` and `rank(T)` with. We could go with `T.order()` and `order(T)` but "ord" instead of "order" could be more convenient. 

It's too bad the terminology is not better!

**Comment by mtfishman** [comment]
I think I have already added `order(T)` as a way to get the number of indices of an ITensor. I would say I prefer `order` instead of `ord` since it is not something you have to type all that much, so it seems better to be more verbose.

I agree that using `rank` for this use case is pretty bad, since it is used so much in linear algebra. I also prefer `order` to something like `ninds`, since "order" is a general tensor terminology but (I think) "index" is more tensor network and ITensor-specific terminology.

**Comment by emstoudenmire** [comment]
Great! Ok I agree with this for all the reasons you said. Good point about another reason not to use ninds. The term order isn't perfect either, but I think it's better than rank; there's no perfect solution so best to keep it simple and consistent. 

(In a more ideal world, I wish "degree" had caught on instead of rank or order. The reason is that order also refers to like the ordering of indices, so it can be confusing in that context!)

**Comment by mtfishman** [comment]
Yeah it is a bit unfortunate. That is why I changed `order(A,i,j,k)` to `permute(A,i,j,k)` for version 3, to avoid that possible confusion.
