### ISSUE TITLE
RC3 - SVD

### ISSUE THREAD

**Issue by jsf15** [ITensor/ITensor#213]
When running TEVOL in RC3 it fails with the following error:

From line 186, file /home/joaosf/itensor/itensor/decomp.h
Error in svd: Arg Maxm is deprecated in favor of MaxDim.

Best regards,
João

**Comment by jsf15** [comment]
Nevermind, please delete this if possible.

**Comment by jsf15** [comment]
Nevermind, please delete this if possible.

**Comment by mtfishman** [comment]
Hi, thanks for the error report. Are you inputting a "Maxm" arg somewhere in your code? In ITensor V3, we are replacing "Maxm" with "MaxDim".

**Comment by mtfishman** [comment]
Ok, no problem. We may decide to allow either "Maxm" or "MaxDim" to not break too much ITensor V2 code, but some of the logic became pretty complicated with that so for now I made using "Maxm" an error. I will try to make the error more clear, in this case it would help to catch the use of "Maxm" in the time evolution functions, instead of lower down in the `svd` function.

**Comment by jsf15** [comment]
The error is clear but either way, I agree it should not break the SVD function.
