### ISSUE TITLE
double free or corruption (out)

### ISSUE THREAD

**Issue by jsf15** [ITensor/ITensor#222]
Calling `replaceInds`  in a loop throws the following error in RC3 
`double free or corruption (out)`

The function works (in my code) three times until it gives this error. Any idea why? 
P.S.: It's not worth putting the code here since it's a bit confusing

**Comment by emstoudenmire** [comment]
Thanks, but in order to look into I would need to see a code that can reproduce the error. Could you please post it?

**Comment by mtfishman** [comment]
That sounds quite strange. Have you tried running in debug mode? 

Basically the function is just a shorthand for: `replaceInds(A,{i,j},{k,l})` -> `A*delta(i,k)*delta(j,l)` with a bit extra to make it work nicely if Indices are swapped. A possible test to see if it is a problem with replaceInds or with something else is if you write what you want to do explicitly in terms of multiplications by `delta`. Beyond that, it would be hard for me to debug without a minimal example of it breaking.

Are you using the latest rc3? Just so you know, I made a small change to replaceInds in the latest commit (https://github.com/ITensor/ITensor/commit/11ab2498691a98655478660592bbae0b265602b4#diff-d5ae31740a13e22c9fac38e0ba0fd3d9R610) to make it work nicer with QN Indices. It may not be relevant to your bug, but just pointing it out since it could change some behavior.

Cheers,
Matt

**Comment by jsf15** [comment]
I just git pulled to generate a minimal working example with the latest version and the latest branch is not compiling (was the wrong branch added?) But I'll look into that tomorrow

**Comment by jsf15** [comment]
Solved with the new version of ITensor. Thank you both!
