### ISSUE TITLE
Missing SVD and index code?

### ISSUE THREAD

**Issue by ryanlevy** [ITensor/ITensor#246]
Hi all,

I have two problems with the v3 code for [entanglement entropy on the website](http://itensor.org/docs.cgi?vers=cppv3&page=formulas/entanglement_mps):

```c++
auto [U,S,V,u,v] = svd(psi(b),{l,s}); //!
```
This fails to compile, and isn't in the decomp header. But it looks like at some point @mtfishman pushed it (9dcb19b5e5f836d5a9155ef3a77865fe5163f505) ...

Then I also can't get `for(auto i : dim(u))` to work, but I'm not sure if that's because it wasn't meant to be used as an `Index` object?

**Comment by emstoudenmire** [comment]
Hi Ryan, thanks for pointing this out too. It is an error with the website. That was the return type at one point (at the time of the commit you linked to), but in the final version of v3 Matt decided to just have the return type be [U,S,V] only. I just updated the website page to fix that. At some point we are going to set up automated testing of all code that appears of the website to systematically catch these things!

Miles

**Comment by ryanlevy** [comment]
Thanks for the reply! Maybe I'm replying this too fast, but the code on the website still won't compile (now because `u` and `v` aren't defined and the lack of iterator for `dim(u)`). I assume adding
```c++
auto u = commonIndex(U,S);
auto v= commonIndex(S,V);
```
and `for(auto i : range1(dim(u)))` will fix that?

**Comment by emstoudenmire** [comment]
Thanks - I was too fast too, and didn't read through the rest of that code formula. It actually had more than one issue, another one unrelated to changing the svd, so I fixed all the issues and just pushed the changes.

You're exactly right about how to fix the code, though I went one step further and just used elt(S,n,n) to get the diagonal elements of S since being on the diagonal the index order doesn't matter.

Best regards,
Miles
