### ISSUE TITLE
Obtaining SiteSet from MPS feature not available in version 3?

### ISSUE THREAD

**Issue by HumpyBlumpy** [ITensor/ITensor#303]
In ITensor 2, there was a way of obtaining a siteset object of an MPS by calling
`psi.sites()`
for some MPS psi.
This was very useful and I have many functions that make use of this feature. For example, I often use it in such form
`psi.sites().op(op_name,site_num);
`
In trying to upgrade to version 3, calling psi.sites() returns an error and I didnt find another way of obtaining it.
Is it possible to bring this feature back? or is there another way of doing this?

**Comment by emstoudenmire** [comment]
Hi, thanks for the question. So the short answer is this feature just isn’t present in version 3. One reason is that we made it easier to construct MPS without requiring a site set, so then we had a situation where in many cases calling psi.sites() would throw an exception because there was no site set associated with psi. (Things could get especially weird when writing MPS to disk and reading them back, because then code relying on calling psi.sites() wouldn’t work unless one remembered to also separately write the site set and read it back in before reading in the MPS again etc.)

Another reason is that we found it was not too hard to pass the site set, if needed, to the same function as the MPS as just a separate variable. 

So the main fix we recommend is just to pass the site set to any function that needs it as a separate variable. But I do understand that can be a pain sometimes when having a very deep stack of function calls.

Another option is to use the new `siteInds` function added in version 3. Given an MPS `psi`, calling `siteInds(psi)` will return a collection of all of the site indices on it. The only drawback is that this collection is not a site set which use can use to obtain physics operators etc. It’s just an array of Index objects. But it’s definitely very helpful for cases where you need the site indices for writing algorithms.

Ok please let us know if you have any more questions that weren’t answered above.
