### ISSUE TITLE
Inheriting from MPO: promotion of MPS inheritance to private

### ISSUE THREAD

**Issue by Jack-Kemp** [ITensor/ITensor#310]
The following "using" lines promote the inherited MPS properties from protected to private. Is this intentional? It means that a derived class cannot use these properties, whereas a derived class of an MPS would be able to, because they are merely protected in the MPS class. Is there a reason why these using statements are not just protected rather than private?

https://github.com/ITensor/ITensor/blob/a251a2e4bae564250335b34b8438759bfe1e54b9/itensor/mps/mpo.h#L26-L36

**Comment by emstoudenmire** [comment]
Good question. Mainly the answer is we hadn't thought about this. The reason is that the inheritance here was just to enable some code reuse (though in hindsight there is probably a better approach to be had; on the Julia side we like using generic functions and when necessary multiple dispatch much better). 

I would say that I'd prefer people not inherit from this class, or really any class in ITensor. Composition (making the class a member of a new class) is generally a cleaner approach for many reasons, whereas inheritance, especially in C++ and especially when the parent class contains data members, is fraught with pitfalls.

**Comment by Jack-Kemp** [comment]
Fair enough. I think from a single dispatch, polymorphic C++ perspective, it is natural to use inheritance for "is-a" relationships, as opposed to the "has-a" relationship of composition. Nevertheless if it's not really recommended I shall refactor my code instead. (I guess the lack of virtual functions, and the fact that MPO inherits from MPS rather than some generic "TensorNetwork" class should have clued me into this!)
