### ISSUE TITLE
Fermion sign when QNs not conserved

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensor#311]
Here is an issue brought up in the support forum (http://www.itensor.org/support/1858/itensor-results-fermions-without-particle-number-conservation). When QNs are not conserved, it looks like the Fermion sign is not being put in correctly by AutoMPO:
```C++
auto N = 2;
auto sites = Fermion(N,{"ConserveQNs",false});
auto ampo = AutoMPO(sites);
for(int b = 1; b <= N-1; ++b)
  {
  ampo += -1,"Cdag",b,"C",b+1;
  ampo += -1,"Cdag",b+1,"C",b;
  }
auto H = toMPO(ampo);
PrintData(H(1)*H(2));
```
returns:
```
H(1)*H(2) = 
ITensor ord=4: (2|id=730|n=1,Site,Fermion)' (2|id=730|n=1,Site,Fermion) (2|id=487|n=2,Site,Fermion) (2|id=487|n=2,Site,Fermion)' 
{norm=1.41 (Dense Real)}
(2,1,2,1) -1.000000
(1,2,1,2) 1.0000000
```
The correct Hamiltonian is returned in ITensor v2, as well as in ITensor v3 when QNs are conserved.

@emstoudenmire, any chance you know what might be going wrong here?

**Comment by emstoudenmire** [comment]
Hm, ok so the reason for this is that AutoMPO checks if an Index is fermionic (i.e. carries at least fermion parity quantum numbers) when constructing the "F" operator. The reason it does this is because it needs to be able to construct "F" for any possible type of site, like even spin or boson sites, so that we can mix these together with fermions.

But when turning off *all* quantum numbers for the Fermion site set that method is failing.

On the other hand, we don't want to force all site sets to have to define "F" just in case they are mixed with fermion sites. So we need a way to determine whether to call a fallback construction of "F".

Perhaps the way to go is just to attempt to call op(sites,"F",j) on a site j, then if it throws an exception catch it and then return an identity operator for F. This is ugly though; I wish I could think of a better way. 

The other alternative is when using fermions, require always using quantum numbers (e.g. make "ConserveQNs=",false not an option for the Fermion site set: you would always have to conserve parity at a minimum). I think this could make more sense and be more elegant, plus it would be more future-proof to other approaches to fermions we're considering. The main drawback I see with this option is that there may be some legitimate cases where you want dense tensors but fermion operators.

**Comment by emstoudenmire** [comment]
I checked and setting "ConserveNf=",false does give the right Hamiltonian here. So it remains just to think through whether we have a good reason to let people turn QNs all the way off for fermions.
