### ISSUE TITLE
excited state DMRG doesn't work w/ Electrons

### ISSUE THREAD

**Issue by ryanlevy** [ITensor/ITensor#318]
Right after entering davidson, itensor crashes with:
```
From line 879, file itensor.cc

div(T1)=QN({"Nf",50,-1},{"Sz",0}) must equal div(T2)=QN() when adding T1+T2
```
This occurs whenever there's an `Electron` in the MixedSiteSet, and for some spin Hamiltonians (see below).

---

To reproduce, take the `mixedspin` sample code and change `using SHalfSOne` to either :
```cpp
using SHalfSOne = MixedSiteSet<SpinHalfSite,ElectronSite>;
```
or 
```cpp
using SHalfSOne = Electron;
```
and add at the bottom of main
```cpp
auto state2 = InitState(sites);
//something generic to start
    for(int i = 1, n = 1; i <= N; i += 2, n += 1)
        {
        if(n%2 == 1) state2.set(i,"Dn");
        else         state2.set(i,"Up");
        }
    for(int i = 2, n = 1; i <= N; i += 2, n += 1)
        {
        if(n%2 == 1) state2.set(i,"Dn");
        else         state2.set(i,"Up");
        }
    auto psi1 = MPS(state2);
    auto wfs = std::vector<MPS>(1);
    wfs.at(0) = psi;
    energy = dmrg(psi1,H,wfs,sweeps,"Quiet");
    printfln("\nGround State Energy = %.10f",energy);
```

This was compiled with ITensor v3 @ 13042c0d

**Comment by emstoudenmire** [comment]
Thanks! Another user reported this issue but we haven't had time to get to it. So I'll try to make it a priority. The test cases are very helpful.

**Comment by zuozw** [comment]
Is this bug fixed? I also need to calculate the excited state.

**Comment by emstoudenmire** [comment]
Just addressed this in PR #341 . Sorry it's been awhile, but if you are able to check this, could you confirm that it's fixed in the latest v3 branch of ITensor? Thanks -

**Comment by zuozw** [comment]
It doesn't work.
After calculating the ground energy, the code throw the message
"From line 479, file /Users/**/ITensor3/itensor/itdata/dotask.h
doTask called on unallocated store pointer
doTask called on unallocated store pointer
Abort trap: 6"


------------------ Original ------------------

**Comment by emstoudenmire** [comment]
Thanks, so now that I fixed the other bug linked in the PR (#341) above, I think I see what's going on in this code and it has a different origin.

The error I got (when running in debug mode to get better error messages) indicates that the initial state `psi1` being used to initialize the excited-state DMRG run has a different total quantum number than the first state `psi`. For this case, what the code should actually do is immediately throw an error with a more helpful error message, because the excited-state DMRG code is only intended for states with the same total QN.

The reason for this is that states with a different total QN are automatically orthogonal, so there's no need to numerically orthogonalize them (as this version of the dmrg code does).

Please let me know if there's another issue either of you find, though, with using this code for wavefunctions with the same total QN.

**Comment by emstoudenmire** [comment]
I just merged a pull request #342 which improves the error message when attempting to mix states with a different total QN in excited-state DMRG.

**Comment by ryanlevy** [comment]
Hi Miles,

I'm not sure what you were referring to about different QN numbers, but the above example does seem to be working now. I also checked my original (more complex) problem and it now runs fine! Thanks!

**Comment by emstoudenmire** [comment]
Great! Thanks for the feedback
