### ISSUE TITLE
Replace orthog with QR

### ISSUE THREAD

**Issue by mtfishman** [ITensor/ITensor#319]
In the custom recursive SVD algorithm in ITensor, the orthogonalization step is currently done with `orthog`, which appears to be taking up most of the time of the total SVD (based on profile data). It may be better to use LAPACK's QR implementation instead.

**Comment by emstoudenmire** [comment]
Yes - this would be a good improvement.

*Importantly*: I found this only works correctly if the QR is constrained such that R has a non-negative diagonal. I believe this is because otherwise it could give a V with some of the vectors inverted relative to the singular values being constrained positive.

We can use the Julia implementation of SVD as a reference. Another improvement from using QR is that afterward, R holds the singular values, so they can be obtained with more numerical precision due to the better numerical stability of QR versus the current approach in the code.
