### ISSUE TITLE
Dont truncate zero singular values with Truncate = False

### ISSUE THREAD

**Issue by HumpyBlumpy** [ITensor/ITensor#340]
Calling position on a MPS truncates zero singular values even if the Truncate arg is false.
`psi.position(1,{"Truncate",false});
`
It seems that the Truncate either does not propagate far enough or gets overwritten somehow?

**Comment by mtfishman** [comment]
Thanks for reporting this. I could definitely believe this is the case (it can be tricky making sure all arguments get passed correctly through a series of functions). Do you have a minimal example for this behavior so we can try to debug what is going on?

**Comment by HumpyBlumpy** [comment]
Thanks for looking into this.

How about this:
```
#include "itensor/all.h"

using namespace itensor;


int main(int argc, char* argv[])
    {

    int N = 5;
    auto sites = SpinHalf(N,{"ConserveQNs",false}); //make a chain of N spin 1/2's
    
    auto state = InitState(sites);
    for(int i = 1; i <= N; ++i) 
        {
        state.set(i,"Dn");
        }
    auto psi = MPS(state);

    Print(averageLinkDim(psi)); // prints 1
    Print(maxLinkDim(psi)); // prints 1


    // Increase the bond dimension (replaces link indices)
    int new_bond_dim = 10;
    for(int i =1; i< N;++i){

        Index ir = rightLinkIndex(psi, i);

        Index ir_new  = Index(new_bond_dim,tags(ir));

        psi.ref(i) *= delta(ir,ir_new);
        psi.ref(i+1) *= delta(ir,ir_new);

    }
    Print(averageLinkDim(psi)); // prints 10
    Print(maxLinkDim(psi)); // prints 10
    psi.position(1,{"Truncate",false});

    Print(averageLinkDim(psi));  // prints 6
    Print(maxLinkDim(psi)); // prints 10


    return 0;
    }
```

**Comment by mtfishman** [comment]
Thanks for a minimal example. I think that is a case where the `"Truncate"` flag is working properly. You can see that if you replace the line `psi.position(1,{"Truncate",false});` with the line `psi.position(1,{"Cutoff=",0});`, the last two lines will print `1` (truncating back down to a product state, as we expect).

The reason why the average link dimension is decreased by the position function is because the links at the edges have a smaller maximum allowable dimension. In your case, if you set the position to 1, then the link dimensions should be {10,8,4,2} (so an average of 6). This can be determined from dimension counting, since the first link has one incoming site index (from the right), so it has a maximum dimension of 2. The second link has two incoming site indices (from the right), so has a maximum dimension of 4, etc. A way to think about this in terms of the svd is that ITensor does a "thin" svd, so for an `m x n` matrix the svd outputs U,S,V with dimension `m x k`, `k x k`, and `k x n` where `k = min(m, n)`. So the decrease in bond dimension is not from a truncation of singular values, but from doing a thin svd.

Also, please note that you shouldn't have to explicitly use `{"Truncate=",false}` if you don't set a `"Cutoff"` or `"MaxDim"`, so you can just call `psi.position(1)`.

**Comment by HumpyBlumpy** [comment]
Oh yes I see, that make sense. That was a stupid thing for me to expect.

Can you please maybe clarify what do people usually mean when they quote a bond dimension then? 
Since the both the average and maximal link dimensions may change by changing the orthogonality center of the MPS.
And what does it mean for 1 site algorithms such as TDVP?

**Comment by mtfishman** [comment]
When people talk about a bond dimension of an MPS, usually it would refer to a "bulk" bond dimension, i.e. in the large system limit, what is a typical bond dimension in the middle of the system (or some distance larger than the correlation length away from the edge of the system). In larger systems, the bond dimension in the bulk shouldn't depend on the orthogonality center. That definition shouldn't depend on what algorithm you are using (it would hold for 1-site or 2-site algorithms).

I'll close this since there isn't a be a bug to fix here.
