### ISSUE TITLE
Compiling ITensor 2.0 with intel icpc failed

### ISSUE THREAD

**Issue by xyu40** [ITensor/ITensor#92]
ITensor 2.0 is very exciting! I cloned it immediately after receiving the email notification. It compiles fine with g++ and PLATFORM=macos, but when I tried icpc with PLATFORM=mkl or macos, the compilation process would encounter the same error message (full output attached). Checking the compiler version with "icpc -v" shows "icpc version 16.0.2 (gcc version 4.9.0 compatibility)". Does someone know what's causing the error? Thanks in advance!
[error.txt](https://github.com/ITensor/ITensor/files/190180/error.txt)

**Comment by emstoudenmire** [comment]
Hi Xiongjie,
Thanks for your enthusiasm! I have not been targeting icpc as one of the supported compilers because I think their C++11 support is not complete. But it would be nice if we could get it to work.

I just pushed a few changes that fix the error you reported, however on my system I still get additional errors when using icpc. But these errors seem to be coming from the standard library now! So it may be that the standard library icpc is using is the one provided with gcc, and is using certain C++11 features not supported by the Intel compiler. However, things may be better on your system, and you have a newer version of the compiler I think.

Please try it out and let me know what errors you see now - 

Miles

**Comment by xyu40** [comment]
Hi Miles,
Thanks for the quick response! I tried the updated version with icpc, compilation aborted at tensor/contract.cc with "error: more than one instance of overloaded function "std::__1::__invoke" matches the argument list".

I think the problem is with intel compiler, because my error message is the same as in this thread -- https://software.intel.com/en-us/forums/intel-c-compiler/topic/610669, in which the problem is acknowledged by intel and will hopefully be fixed in intel compiler 2016 update 3.

I will continue exploring ITensor 2 with GNU compilers until intel fixes this.

Cheers,
Xiongjie

**Comment by emstoudenmire** [comment]
Hi Xiongjie,
Yes, that is what I suspected: that unfortunately the Intel compiler hasn't really kept up with the new C++11 standard. I'm very interested in supporting it, however, so if you hear that they make some updates please give it another try in the future and let me know if it still fails to compile for a reason related to ITensor itself.

For now I'll close this issue -

Best,
Miles
